# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], max_length=200)),
                ('date_due', models.DateField(verbose_name='Due Date')),
            ],
        ),
    ]
