# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_todolist_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='color_code',
            field=models.CharField(max_length=6),
        ),
    ]
