# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20170222_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='state',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], default='To Do', max_length=200),
        ),
    ]
