# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_auto_20170222_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='color_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
